version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
  tal:
    build:
      context: ./
    command: "./gradlew run"
    container_name: tal-runner
    ports:
      - "5050:5005"
    depends_on:
      - dynamodb-local
    working_dir: /app
    env_file:
      - .env
